apiVersion: v1
kind: ConfigMap
metadata:
  name: php-nginx
  namespace: mark-k8s-dev
  labels:
    app: php-nginx
data:
  php-nginx.conf: |
    # php---nginx config
    server {
      listen 80;
      #server_name myapp.com;

      root /app;

      location / {
        try_files $uri $uri/index.php;
      }

      location ~ \.php$ {
        # fastcgi_pass [PHP_FPM_LINK_NAME]:9000;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
