apiVersion: v1
kind: Service
metadata:
  name: php-fpm-nginx-service
  namespace: mark-k8s-dev
  labels:
    app: php-fpm-nginx-service
spec:
  type: NodePort
  selector:
    app: php-fpm-nginx
  ports:
  - name: port1
    protocol: TCP
    port: 80 # 服务端口, 内部可访问
    targetPort: 80 #Pod端口
    
