apiVersion: v1
kind: Service
metadata:
  name: mysql-single-service
  namespace: mark-k8s-dev
  labels:
    app: mysql-single-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: mysql-single
  ports:
  - protocol: TCP
    port: 3306 # 服务端口, 内部可访问
    targetPort: 3306 #Pod端口
