apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-single
  namespace: mark-k8s-dev
  labels:
    app: mysql-single
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-single
  template:
    metadata:
      labels:
        app: mysql-single
    spec:
      containers:
        - name: mysql-single
          image: docker-harbor.clubs999.com/public/mysql:5.7
          args: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_general_ci","--server-id=100","--log-bin=mysql-bin"]
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql/mysql-single" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/var/log/mysql"
              subPath: "mysql/mysql-single-log" #文件路径,以挂载的pvc为基准
              name: mysql-data
            - mountPath: "/etc/mysql/my.cnf"
              subPath: "mysql.cnf"
              name: mysql-cnf
          env:
            - name: MYSQL_ROOT_PASSWORD #设置MySQL的root密码
              value: "123456"
            - name: TZ
              value: Asia/Shanghai

      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub
        - name: mysql-cnf
          configMap:
            name: mysql
