apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: mark-k8s-dev
  labels:
    app: etcd-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: etcd
  ports:
  - name: port1
    protocol: TCP
    port: 2379 #服务端口, 内部可访问
    targetPort: 2379 #Pod端口
  - name: port2
    protocol: TCP
    port: 2380 #服务端口, 内部可访问
    targetPort: 2380 #Pod端口
