apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-1-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: zookeeper-1
  ports:
  - name: port1
    protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口
  - name: port2
    protocol: TCP
    port: 2888 # 服务端口, 内部可访问
    targetPort: 2888 #Pod端口
  - name: port3
    protocol: TCP
    port: 3888 # 服务端口, 内部可访问
    targetPort: 3888 #Pod端口
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-2-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: zookeeper-2
  ports:
  - name: port1
    protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口
  - name: port2
    protocol: TCP
    port: 2888 # 服务端口, 内部可访问
    targetPort: 2888 #Pod端口
  - name: port3
    protocol: TCP
    port: 3888 # 服务端口, 内部可访问
    targetPort: 3888 #Pod端口

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-3-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: zookeeper-3
  ports:
  - name: port1
    protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口
  - name: port2
    protocol: TCP
    port: 2888 # 服务端口, 内部可访问
    targetPort: 2888 #Pod端口
  - name: port3
    protocol: TCP
    port: 3888 # 服务端口, 内部可访问
    targetPort: 3888 #Pod端口