apiVersion: v1
kind: Service
metadata:
  name: zookeeper2181-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper2181-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: zookeeper2181
  ports:
  - name: port1
    protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口
    

    