apiVersion: v1
kind: Service
metadata:
  name: jbosstest-service
  namespace: mark-k8s-dev
  labels:
    app: jbosstest-service
spec:
  type: NodePort
  selector:
    app: jbosstest
  ports:
  - name: port1
    protocol: TCP
    port: 8080 #服务端口, 内部可访问
    targetPort: 8080 #Pod端口
    
