apiVersion: v1
kind: Service
metadata:
  name: nginx-tcp-service
  namespace: mark-k8s-dev
  labels:
    app: nginx-tcp-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: nginx-tcp
  ports:
  - name: port1
    protocol: TCP
    port: 1521 # 服务端口, 内部可访问
    targetPort: 1521 #Pod端口
    
