apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: mark-k8s-dev
  labels:
    app: rabbitmq-service
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: port1
    protocol: TCP
    port: 4369 # 服务端口, 内部可访问
    targetPort: 4369 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 5672 # 服务端口, 内部可访问
    targetPort: 5672 #Pod端口

  - name: port3
    protocol: TCP
    port: 25672 # 服务端口, 内部可访问
    targetPort: 25672 #Pod端口

  - name: port4
    protocol: TCP
    port: 15672 # 服务端口, 内部可访问
    targetPort: 15672 #Pod端口