apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: mark-k8s-dev
  labels:
    app: haproxy-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: haproxy
  ports:
  - name: port1
    protocol: TCP
    port: 80 # 服务端口, 内部可访问
    targetPort: 80 #Pod端口
    
