#由于fastdfs会识别客户端ip，所以不能使用service访问，可以不创建service
apiVersion: v1
kind: Service
metadata:
  name: fastdfs-service
  namespace: mark-k8s-dev
  labels:
    app: fastdfs-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  clusterIP: 10.96.130.100
  selector:
    app: fastdfs
  ports:
  - name: port1
    protocol: TCP
    port: 22122 #服务端口, 内部可访问
    targetPort: 22122 #Pod端口
  - name: port2
    protocol: TCP
    port: 23000 #服务端口, 内部可访问
    targetPort: 23000 #Pod端口 
  - name: port3
    protocol: TCP
    port: 8088 #服务端口, 内部可访问
    targetPort: 8088 #Pod端口 