apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb-service
  namespace: mark-k8s-dev
  labels:
    app: wordpress-mariadb-service
spec:
  type: NodePort
  selector:
    app: wordpress-mariadb
  ports:
  - name: port1
    protocol: TCP
    port: 8080 # 服务端口, 内部可访问
    targetPort: 8080 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 8443 # 服务端口, 内部可访问
    targetPort: 8443 #Pod端口

  - name: port3
    protocol: TCP
    port: 3306 # 服务端口, 内部可访问
    targetPort: 3306 #Pod端口