apiVersion: apps/v1
kind: Deployment
metadata:
  name: nacos
  namespace: mark-k8s-dev
  labels:
    app: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
    spec:
      containers:
        - name: nacos
          image: docker-harbor.clubs999.com/public/nacos/nacos-server:1.4.1
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 7848
              name: rpc
          env:
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: MODE
              value: "standalone"
          volumeMounts:
            - name: nacos-data
              mountPath: /home/nacos/plugins/peer-finder
              subPath: "nacos/peer-finder"
            - name: nacos-data
              mountPath: /home/nacos/data
              subPath: "nacos/data"
            - name: nacos-data
              mountPath: /home/nacos/logs
              subPath: "nacos/logs"
      volumes:
        - name: nacos-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub