apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: docker-harbor.clubs999.com/public/jenkins/jenkins:lts-centos7
          securityContext:
            enabled: true
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            fsGroup: 0
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              subPath: "jenkins/data" #文件路径,以挂载的pvc为基准
              name: jenkins-data

          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: JAVA_OPTS
              value: "-Duser.timezone=Asia/Shanghai"


      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: gluster-claim-jenkins
