apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-kafka
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-kafka
  template:
    metadata:
      labels:
        app: zookeeper-kafka
    spec:
      containers:
        - name: zookeeper-kafka
          image: docker-harbor.clubs999.com/public/bitnami/zookeeper
          securityContext:
            enabled: true
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            fsGroup: 0
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: "/bitnami/zookeeper"
              subPath: "kafka/zookeeper-kafka" #文件路径,以挂载的pvc为基准
              name: zookeeper-kafka-data
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"

      volumes:
        - name: zookeeper-kafka-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
  namespace: mark-k8s-dev
  labels:
    app: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: docker-harbor.clubs999.com/public/bitnami/kafka
          securityContext:
            enabled: true
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            fsGroup: 0
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: "/bitnami"
              subPath: "kafka/kafka-1" #文件路径,以挂载的pvc为基准
              name: kafka-data
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-kafka-service:2181"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-1-service:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "false"

      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-2
  namespace: mark-k8s-dev
  labels:
    app: kafka-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-2
  template:
    metadata:
      labels:
        app: kafka-2
    spec:
      containers:
        - name: kafka-2
          image: docker-harbor.clubs999.com/public/bitnami/kafka
          securityContext:
            enabled: true
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            fsGroup: 0
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: "/bitnami"
              subPath: "kafka/kafka-2" #文件路径,以挂载的pvc为基准
              name: kafka-data
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-kafka-service:2181"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-2-service:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "false"

      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-3
  namespace: mark-k8s-dev
  labels:
    app: kafka-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-3
  template:
    metadata:
      labels:
        app: kafka-3
    spec:
      containers:
        - name: kafka-3
          image: docker-harbor.clubs999.com/public/bitnami/kafka
          securityContext:
            enabled: true
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            fsGroup: 0
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: "/bitnami"
              subPath: "kafka/kafka-3" #文件路径,以挂载的pvc为基准
              name: kafka-data
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper-kafka-service:2181"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-3-service:9092"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: "false"

      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: gluster-claim-pub

