apiVersion: v1
kind: Service
metadata:
  name: zookeeper-kafka-service
  namespace: mark-k8s-dev
  labels:
    app: zookeeper-kafka-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: zookeeper-kafka
  ports:
  - protocol: TCP
    port: 2181 # 服务端口, 内部可访问
    targetPort: 2181 #Pod端口

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-1-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: kafka-1
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-2-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: kafka-2
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-3-service
  namespace: mark-k8s-dev
  labels:
    app: kafka-3-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: kafka-3
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092
