apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: tinode-chat
  labels:
    app: influxdb-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: influxdb
  ports:
  - name: port1
    protocol: TCP
    port: 8086 # 服务端口, 内部可访问
    targetPort: 8086 #Pod端口
  - name: port2
    protocol: TCP
    port: 8088 # 服务端口, 内部可访问
    targetPort: 8088 #Pod端口   
