apiVersion: v1
kind: Service
metadata:
  name: nsq-service
  namespace: mark-k8s-dev
  labels:
    app: nsq-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: nsq
  ports:
  - name: port1
    protocol: TCP
    port: 4150 # 服务端口, 内部可访问
    targetPort: 4150 #Pod端口
    
  - name: port2
    protocol: TCP
    port: 4151 # 服务端口, 内部可访问
    targetPort: 4151 #Pod端口

  - name: port3
    protocol: TCP
    port: 4160 # 服务端口, 内部可访问
    targetPort: 4160 #Pod端口

  - name: port4
    protocol: TCP
    port: 4161 # 服务端口, 内部可访问
    targetPort: 4161 #Pod端口

  - name: port5
    protocol: TCP
    port: 4171 # 服务端口, 内部可访问
    targetPort: 4171 #Pod端口