apiVersion: v1
kind: Service
metadata:
  name: redis-6379-service
  namespace: redis
  labels:
    app: redis-6379-service
spec:
  type: ClusterIP #ClusterIP,如果不需要开放出去，可以改成ClusterIP，这样就不会创建随机端口到宿主机上面;NodePort 开放端口到宿主机
  selector:
    app: redis6379
  ports:
  - protocol: TCP
    port: 6379 # 服务端口, 内部可访问
    targetPort: 6379 #Pod端口
    nodePort: 33060 #node开放的端口,外部访问